#!/usr/bin/env python3
"""Adjust the kernel_aarch64 entry in common/BUILD.bazel for a modified defconfig.

Why this exists as a script rather than a sed one-liner:
`kernel_aarch64` is NOT declared as a literal `kernel_build(name = "kernel_aarch64")`
in android15-6.6. It is generated by the macro

    define_common_kernels(target_configs = {
        "kernel_aarch64": { ... },
        ...
    })

so a sed looking for `name = "kernel_aarch64",` matches nothing and silently
no-ops — which is exactly how a `savedefconfig does not match` failure slipped
through. The settings have to be injected into that dict entry instead.

Changes applied to the "kernel_aarch64" entry:
  * check_defconfig = "disabled"
      Our Droidspaces/KSU options are appended to gki_defconfig rather than being
      inserted in `savedefconfig` order, so the default "match" check fails on
      ordering alone.
  * kmi_symbol_list_strict_mode = False
      The Droidspaces kABI patch deliberately moves task_struct members into
      padding, which shifts some CRCs. That is the point of the padding, but
      strict mode still aborts on it.
  * protected_exports_list / protected_modules_list removed
      apply-root.sh deletes android/abi_gki_protected_exports_* (required on GKI
      android14+ or WiFi modules refuse to load); leaving the reference behind
      would break the build with a missing-file error.
"""
import re
import sys


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: patch-bazel-target.py <path/to/common/BUILD.bazel>", file=sys.stderr)
        return 2
    path = sys.argv[1]
    src = open(path, encoding="utf-8").read()

    if '"check_defconfig": "disabled"' in src:
        print("    BUILD.bazel already patched")
        return 0

    # Locate the "kernel_aarch64" key, then its brace-balanced dict value. Brace
    # matching (rather than a regex for the closing brace) keeps nested lists and
    # dicts from ending the match early.
    m = re.search(r'^\s*"kernel_aarch64":\s*\{', src, re.MULTILINE)
    if not m:
        print("::error::could not find the \"kernel_aarch64\" entry in target_configs",
              file=sys.stderr)
        print("::error::BUILD.bazel layout changed; refusing to build with an unchecked defconfig",
              file=sys.stderr)
        return 1

    open_idx = src.index("{", m.start())
    depth = 0
    close_idx = None
    for i in range(open_idx, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                close_idx = i
                break
    if close_idx is None:
        print("::error::unbalanced braces in kernel_aarch64 entry", file=sys.stderr)
        return 1

    body = src[open_idx + 1:close_idx]

    # Drop references to the protected-exports files we remove.
    dropped = []
    for key in ("protected_exports_list", "protected_modules_list"):
        new_body, n = re.subn(rf'^\s*"{key}":[^\n]*\n', "", body, flags=re.MULTILINE)
        if n:
            body = new_body
            dropped.append(key)

    # Relax strict KMI mode if present; otherwise it is added below.
    body, n_strict = re.subn(
        r'"kmi_symbol_list_strict_mode":\s*True',
        '"kmi_symbol_list_strict_mode": False',
        body,
    )

    indent = "        "
    additions = [f'{indent}"check_defconfig": "disabled",']
    if not n_strict:
        additions.append(f'{indent}"kmi_symbol_list_strict_mode": False,')

    body = body.rstrip()
    if not body.endswith(","):
        body += ","
    body += "\n" + "\n".join(additions) + "\n    "

    out = src[:open_idx + 1] + body + src[close_idx:]
    open(path, "w", encoding="utf-8").write(out)

    print('    check_defconfig -> "disabled"')
    print(f"    kmi_symbol_list_strict_mode -> False ({'replaced' if n_strict else 'added'})")
    if dropped:
        print(f"    removed: {', '.join(dropped)}")

    # Re-read and assert, so a silent no-op can never pass again.
    check = open(path, encoding="utf-8").read()
    if '"check_defconfig": "disabled"' not in check:
        print("::error::verification failed: check_defconfig not present after write", file=sys.stderr)
        return 1
    print("    verified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
