#!/usr/bin/env python3
"""Adjust the kernel_aarch64 entry in common/BUILD.bazel.

Two dead ends worth recording, because both look correct:

1. `sed '/name = "kernel_aarch64",/a ...'`
   `kernel_aarch64` is NOT a literal `kernel_build(name = "kernel_aarch64")` on
   android15-6.6. It is generated by
       define_common_kernels(target_configs = {"kernel_aarch64": {...}})
   so the sed matched nothing and silently no-opped. The savedefconfig check stayed
   on and the build failed with "savedefconfig does not match gki_defconfig".

2. Injecting `"check_defconfig": "disabled"` into that dict.
   `check_defconfig` is a real `kernel_build` attribute, but `define_common_kernels`
   does not forward it. `_define_common_kernel()` in
   build/kernel/kleaf/common_kernels.bzl (branch `main-kernel-build-2024`, which is
   what the manifest pins for kernel/build) takes a fixed keyword list with no
   `check_defconfig`, so bazel fails at load time with:
       Error: _define_common_kernel() got unexpected keyword argument: check_defconfig

The defconfig check that actually fires is the legacy build-config hook
`POST_DEFCONFIG_CMDS="check_defconfig"` in `common/build.config.gki`, which kleaf
still evaluates. It is neutralised there — see scripts/fix-gki-config.sh.

So this script only changes what `_define_common_kernel` really accepts:
  * kmi_symbol_list_strict_mode = False
      The Droidspaces kABI patch moves task_struct members into padding, shifting
      some CRCs by design; strict mode aborts on exactly that.
  * trim_nonlisted_kmi = False
      Stock (MiCode tree) exports ~7830 symbols; trimming to Google's KMI list
      can drop symbols Xiaomi's prebuilt vendor_dlkm modules import ("unknown
      symbol" at load). Keep every export the source tree has.
  * protected_exports_list / protected_modules_list dropped
      apply-root.sh deletes android/abi_gki_protected_exports_* so Google-signed
      system_dlkm modules (rfkill, bluetooth, ...) can load in a self-signed kernel.
      Leaving the references would fail the build on a missing file.
"""
import re
import sys

MARKER = "# dsh: kernel_aarch64 patched"


def find_entry(src, key):
    """Return (open_idx, close_idx) for the brace-balanced dict value of `key`."""
    m = re.search(rf'^\s*"{key}":\s*\{{', src, re.MULTILINE)
    if not m:
        return None
    open_idx = src.index("{", m.start())
    depth = 0
    for i in range(open_idx, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return open_idx, i
    return None


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: patch-bazel-target.py <path/to/common/BUILD.bazel>", file=sys.stderr)
        return 2
    path = sys.argv[1]
    src = open(path, encoding="utf-8").read()

    if MARKER in src:
        print("    BUILD.bazel already patched")
        return 0

    found = find_entry(src, "kernel_aarch64")
    if not found:
        print('::error::could not find the "kernel_aarch64" entry in target_configs',
              file=sys.stderr)
        print("::error::BUILD.bazel layout changed; refusing to build unverified",
              file=sys.stderr)
        return 1
    open_idx, close_idx = found
    body = src[open_idx + 1:close_idx]

    dropped = []
    for key in ("protected_exports_list", "protected_modules_list"):
        new_body, n = re.subn(rf'^\s*"{key}":[^\n]*\n', "", body, flags=re.MULTILINE)
        if n:
            body = new_body
            dropped.append(key)

    body, n_strict = re.subn(
        r'"kmi_symbol_list_strict_mode":\s*True',
        '"kmi_symbol_list_strict_mode": False',
        body,
    )

    indent = "        "
    if not n_strict and '"kmi_symbol_list_strict_mode"' not in body:
        body = body.rstrip()
        if not body.endswith(","):
            body += ","
        body += f'\n{indent}"kmi_symbol_list_strict_mode": False,'

    body, n_trim = re.subn(
        r'"trim_nonlisted_kmi":\s*[A-Za-z_][A-Za-z0-9_]*',
        '"trim_nonlisted_kmi": False',
        body,
    )
    if not n_trim and '"trim_nonlisted_kmi"' not in body:
        body = body.rstrip()
        if not body.endswith(","):
            body += ","
        body += f'\n{indent}"trim_nonlisted_kmi": False,'

    body = body.rstrip()
    if not body.endswith(","):
        body += ","
    body += f"\n{indent}{MARKER}\n    "

    out = src[:open_idx + 1] + body + src[close_idx:]
    open(path, "w", encoding="utf-8").write(out)

    print(f"    kmi_symbol_list_strict_mode -> False ({'replaced' if n_strict else 'added'})")
    print(f"    trim_nonlisted_kmi -> False ({'replaced' if n_trim else 'added'})")
    if dropped:
        print(f"    removed: {', '.join(dropped)}")

    # Re-read and assert: a silent no-op must never pass again.
    check = open(path, encoding="utf-8").read()
    if MARKER not in check or '"kmi_symbol_list_strict_mode": False' not in check \
            or '"trim_nonlisted_kmi": False' not in check:
        print("::error::verification failed after write", file=sys.stderr)
        return 1
    print("    verified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
